#!/usr/bin/env bash
#bash script accepting 2 arguments from a subdomain and pointing to a destination IP
print_domain_record () {
    record_and_ip=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tail -1 | awk '{print $4, $NF}')
    echo "$2" $record_and_ip | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 2 ]; then
    print_domain_record "$1" "$2"
else
    for sub in "www" "lb-01" "web-01" "web-02"; do
        print_domain_record "$1" "$sub"
    done
fi

